#! /bin/bash

#define icons for workspaces 1-9
ic=(0 "" "󰈹" "" "󰍧", "󰓇")

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
  export f"$num"="$num"
  export fnum=f"$num"
done

workspaces() {
if [[ ${1:0:4} == "workspace" ]]; then #set focused workspace
  unset -v "$fnum"
  num=w${1:11}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=w${1:17}
  export o"$num"="$num"
  export f"$num"="$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=w${1:18}
  unset -v o"$num" f"$num"
fi

#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"v\" :space-evenly \"false\" 	\
              (button :onclick \"hyprctl dispatch workspace 1\" :onrightclick \"hyprctl dispatch workspace 1 && /home/filipe/.config/hypr/default_app\" :class \"0$o1$f1\" \"${ic[1]}\") \
              (button :onclick \"hyprctl dispatch workspace 2\" :onrightclick \"hyprctl dispatch workspace 2 && /home/filipe/.config/hypr/default_app\"	:class \"0$o2$f2\" \"${ic[2]}\") \
              (button :onclick \"hyprctl dispatch workspace 3\" :onrightclick \"hyprctl dispatch workspace 3 && /home/filipe/.config/hypr/default_app\"	:class \"0$o3$f3\" \"${ic[3]}\") \
              (button :onclick \"hyprctl dispatch workspace 4\" :onrightclick \"hyprctl dispatch workspace 4 && /home/filipe/.config/hypr/default_app\"	:class \"0$o4$f4\" \"${ic[4]}\") \
              (button :onclick \"hyprctl dispatch workspace 5\" :onrightclick \"hyprctl dispatch workspace 5 && /home/filipe/.config/hypr/default_app\"	:class \"0$o4$f5\" \"${ic[5]}\") \
          )\
        )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
done
